### PR TITLE
Serve JSON files from Amazon S3

### PR DESCRIPTION
**Pull request by mberth**
We want to move the approx 3200 JSON files out of the github repository, see https://github.com/obuchel/classification/issues/4. The simplest solution is to serve them from an S3 bucket.

With the changes in this PR we can

- setup an S3 bucket `ecv-county-maps` to store classification data and county + state boundaries
- upload generated data to S3
- change maps to use S3 by default, instead of GitHub
- keep using locally generated files during development

See the [README.md](https://github.com/obuchel/classification/pull/13/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) for more details.

## Notes

I have moved the files for state and county boundaries to `data/geo`. Other (experimental) maps may rely on these files being served by GitHub, they should be adapted.

## Deployment

- Merge this pull request
- The maps at https://www.endcoronavirus.org/us-counties should still take their JSON data from GitHub at this point. Check that they still work.

The S3 bucket should be owned by NECSI, as they will have to pay for the traffic. See https://github.com/obuchel/classification/issues/4 for a cost estimate. 

Create the S3 bucket and upload data to it as described in  [README.md](https://github.com/obuchel/classification/pull/13/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8). That will need the AWS credentials of someone at NECSI.

Switch to serving by S3:

- in SquareSpace, edit the page for https://www.endcoronavirus.org/us-counties
- find the IFrame and change `https://obuchel.github.io/classification/classification_map.html` to
   `https://obuchel.github.io/classification/classification_map.html?useS3=true`
- use the browser console to check that JSON files are now retrieved from S3
- make a similar change to the other map. Check again that S3 is used.

## Steps for future Pull Requests

- remove a few thousand JSON files from the repository 
- automate the daily update of the maps with GitHub actions
- make serving from S3 the default (remove the parameter `useS3=true`)

### CODE REVIEW

**Comment by obuchel** [comment]
Let's leave these files for now.

**Comment by mberth** [comment]
> Let's leave these files for now.

You mean you don't want to switch to S3? Or you want to keep states.json and counties.json at their original places?

**Comment by mberth** [comment]
Sorry, this needs a little more time. I have run into CORS related problems since the Javascript code was extracted to map_impl.js etc.

**Comment by obuchel** [comment]
I prefer not to pay extra for S3. It is enough that we are paying for Amazon.

**Comment by mberth** [comment]
Closed in favor of #16

**Pull request closed without merging**
